server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring-boot-app
    static_configs:
      - targets:
          - webflux-app
        labels:
          job: spring-boot-app
          service: template
          environment: development
          app_name: webflux-app
          __path__: /var/log/app/*.log

    # Parse Spring Boot logs
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) \[(?P<thread>.*?)\] (?P<level>\w+)\s+(?P<logger>.*?) - (?P<message>.*)'

      - labels:
          level:
          thread:
          logger:

      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05'

      - output:
          source: message