global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/management/prometheus'
    static_configs:
      - targets: ['webflux-app:8080']
        labels:
          app_name: webflux-app